component: scf
name: twinlife-api
app: twinlife
stage: dev

inputs:
  src: ./dist
  handler: index.handler
  runtime: Nodejs16.13
  region: ap-guangzhou
  description: Twinlife API Service
  memorySize: 128
  timeout: 10
  environment:
    variables:
      DB_HOST: gz-cdb-atwbmi17.sql.tencentcdb.com
      DB_PORT: 22423
      DB_USER: root
      DB_PASSWORD: km9906219327L#
      DB_DATABASE: twinlife
      JWT_SECRET: your-secret-key
      JWT_EXPIRES_IN: 7d
      CODE_EXPIRES_IN: 300
      CODE_LENGTH: 6
      NODE_ENV: production
  
  events:
    - http:
        name: http-trigger
        enable: true
        transport: HTTPS
        integratedResponse: true
        cors: true
        protocols:
          - http
          - https 